### PR TITLE
Add attached text type for components and BOM level metadata

### PR DESCRIPTION
**Pull request by coderpatros**
First cut of #49 

Feedback most welcome. Especially before I go to the trouble of making tests :)

### CODE REVIEW

**Comment by stevespringett** [comment]
My only recommendation for this is to include an OPTIONAL `name` or `title` that describes what is being attached.

Example:
```xml
<attachments>
    <attachment name="Installation Instructions" content-type="text/plain" encoding="base64">VGVzdGluZyBUZXN0aW5nIDEtMi0z</attachment>
</attachments>
```

I have no opinion on whether its called `name` or `title` or something else. If there is somewhere else in the schema where we use a similar label, we should strive for consistence where possible.

**Comment by stevespringett** [comment]
What impact will this have on the other fields that rely on attachmentType? I think license and swid rely on this. Would this recommendation break or add confusion to other uses?

**Comment by coderpatros** [comment]
I'm thinking maybe leave attached text as is. And maybe something like this? With the contents element being the existing attachedTextType.

```
<attachments>
    <attachment>
        <name>Installation Instructions</name>
        <description>extended description</description>
        <contents content-type="text/plain" encoding="base64">VGVzdGluZyBUZXN0aW5nIDEtMi0z</contents>
    </attachment>
</attachments>
```

**Comment by stevespringett** [comment]
Good suggestion as it doesn't impact existing uses, but gives additional context to this use case.

**Comment by coderpatros** [comment]
No test data yet, but reviews welcome.

**Pull request closed without merging**
