### PR TITLE
feat: decouple metadata from its component

### LINKED ISSUE #57: Rename "manufacture" to "manufacturer"?
Would it be possible to rename "manufacture" to "manufacturer" (or deprecate old and add new)? 

Maybe something like:

```
diff --git a/schema/bom-1.3-SNAPSHOT.schema.json b/schema/bom-1.3-SNAPSHOT.schema.json
index 8787ba7..e02949e 100644
--- a/schema/bom-1.3-SNAPSHOT.schema.json
+++ b/schema/bom-1.3-SNAPSHOT.schema.json
@@ -107,8 +107,8 @@
           "description": "The component that the BOM describes.",
           "$ref": "#/definitions/component"
         },
-        "manufacture": {
-          "title": "Manufacture",
+        "manufacturer": {
+          "title": "Manufacturer",
           "description": "The organization that manufactured the component that the BOM describes.",
           "$ref": "#/definitions/organizationalEntity"
         },
diff --git a/schema/bom-1.3-SNAPSHOT.xsd b/schema/bom-1.3-SNAPSHOT.xsd
index 9119864..dfe283c 100644
--- a/schema/bom-1.3-SNAPSHOT.xsd
+++ b/schema/bom-1.3-SNAPSHOT.xsd
@@ -71,7 +71,7 @@ limitations under the License.
                     <xs:documentation>The component that the BOM describes.</xs:documentation>
                 </xs:annotation>
             </xs:element>
-            <xs:element name="manufacture" type="bom:organizationalEntity" minOccurs="0" maxOccurs="unbounded">
+            <xs:element name="manufacturer" type="bom:organizationalEntity" minOccurs="0" maxOccurs="unbounded">
                 <xs:annotation>
                     <xs:documentation>The organization that manufactured the component that the BOM describes.</xs:documentation>
                 </xs:annotation>
@@ -231,7 +231,7 @@ limitations under the License.
             <xs:element name="supplier" type="bom:organizationalEntity" minOccurs="0" maxOccurs="1">
                 <xs:annotation>
                     <xs:documentation>The organization that supplied the component. The supplier may often
-                        be the manufacture, but may also be a distributor or repackager.</xs:documentation>
+                        be the manufacturer, but may also be a distributor or repackager.</xs:documentation>
                 </xs:annotation>
             </xs:element>
             <xs:element name="author" type="xs:normalizedString" minOccurs="0" maxOccurs="1">
diff --git a/schema/ext/bom-descriptor-1.0.xsd b/schema/ext/bom-descriptor-1.0.xsd
index 013f550..cc6447b 100644
--- a/schema/ext/bom-descriptor-1.0.xsd
+++ b/schema/ext/bom-descriptor-1.0.xsd
@@ -66,7 +66,7 @@ limitations under the License.
           <xs:documentation>The component that the BOM describes.</xs:documentation>
         </xs:annotation>
       </xs:element>
-      <xs:element name="manufacture" type="bd:organizationalEntity" minOccurs="0" maxOccurs="unbounded">
+      <xs:element name="manufacturer" type="bd:organizationalEntity" minOccurs="0" maxOccurs="unbounded">
         <xs:annotation>
           <xs:documentation>The organization that manufactured the component that the BOM describes.</xs:documentation>
         </xs:annotation>
```

And the examples (noting 1.2 can't be changed) would then be:
```
diff --git a/tools/src/test/resources/valid-metadata-manufacture-1.2.json b/tools/src/test/resources/valid-metadata-manufacture-1.2.json
index fb92230..68c7aff 100644
--- a/tools/src/test/resources/valid-metadata-manufacture-1.2.json
+++ b/tools/src/test/resources/valid-metadata-manufacture-1.2.json
@@ -4,7 +4,7 @@
   "serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
   "version": 1,
   "metadata": {
-    "manufacture": {
+    "manufacturer": {
       "name": "Acme, Inc.",
       "url": [
         "https://example.com"
diff --git a/tools/src/test/resources/valid-metadata-manufacture-1.2.xml b/tools/src/test/resources/valid-metadata-manufacture-1.2.xml
index b6773a5..c6313d4 100644
--- a/tools/src/test/resources/valid-metadata-manufacture-1.2.xml
+++ b/tools/src/test/resources/valid-metadata-manufacture-1.2.xml
@@ -1,14 +1,14 @@
 <?xml version="1.0"?>
 <bom serialNumber="urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79" version="1" xmlns="http://cyclonedx.org/schema/bom/1.2">
     <metadata>
-        <manufacture>
+        <manufacturer>
             <name>Acme, Inc.</name>
             <url>https://example.com</url>
             <contact>
                 <name>Acme Professional Services</name>
                 <email>professional.services@example.com</email>
             </contact>
-        </manufacture>
+        </manufacturer>
     </metadata>
     <components />
 </bom>
```

### LINKED ISSUE #335: feat: multiple component authors
Currently, component's author is a single item.
It might appear, that more than one entity is authoring a component. Therefore, I'd suggest having component's author a list, rather than a single string. a list of "organizationalContact" would be great

see also:  https://github.com/CycloneDX/specification/issues/27

### LINKED ISSUE #346: Should `manufacture` be a property of `component`, rather than `metadata`?
The majority of fields under `metadata` refer to the BOM itself. 

However, `metadata.manufacture` technically refers to `metadata.component`:

https://github.com/CycloneDX/specification/blob/299209abd9531d808e0cc4235e77a7c4b1b53d96/schema/bom-1.5.schema.json#L263-L267

This can cause confusion because, as mentioned, everything else refers to the BOM, not `metadata.component`.

Should `manufacture` be a property of `component` instead, to make the association more clear?

### PR DESCRIPTION
**Pull request by jkowalleck**
The following changes were made with the intent to not introduce breaking changes,
neither syntactic nor semantic(!)

## Changes 

- add `component.manufacturer` as "OrganizationalEntity"
  -- fixes #346
- add `component.authors` as list of "OrganizationalContact"
  -- fixes #335
- deprecate `component.author` in favour of `component.authors` and `component.manufacturer`
  - reason: value was described to be a string that could represent person(s) or organization(s). 
    So let's introduce dedicated fields for both of these: 
    Organizations are represented by the new `@.manufacturer` &
    persons are represented by the new `@.authors`.
- add `metatada.manufaturer` as "OrganizationalEntity"
  -- fixes #57
- deprecate `metatada.manufature` in favour of `metadata.component.manufacturer`
  -- fixes #346

----

## TODO
- [x] update JSON schema
- [x] update XSD
- [x] update protobuff schema
- [x] add examples and test resources

## Follow up tasks
- [ ] update use cases on the Website
- [ ] update SBOM guide
- [ ] create a BC task for 2.0: remove deprecated `metadata.manufacture`
- [ ] create a BC task for 2.0: remove deprecated `component.author`

### CODE REVIEW

**Comment by jkowalleck** [comment]
current state supersedes #370 #372
current state is a basis for further discussions.

**Comment by jkowalleck** [comment]
originally i had planned 
the following: 
- deprecate  `metadata.supplier` in favour of `metadta.component.supplier` 
  -- fixes #345

in a discussion with members of the CoreWorkingGroup, they told to do the following instead:
- state in the description, that `metadata.supplier` so that it stated
  - `< 1.6`, the meaning was "supplier of the component described by the BOM"  (old/legacy)
  - `>= 1.6`, the meaning will be "supplier of the BOM" 
     previous capability would be shifted to in favour of `metadata.component.supplier`

the proposal would cause breaking semantic changes. I do not want to bring any breaking change into the spec.
Therefore I will drop the aspect 'supplier' entirely from this PR.

**Comment by nscuro** [comment]
> the proposal would cause breaking semantic changes. I do not want to bring any breaking change into the spec.
Therefore I will drop the aspect 'supplier' entirely from this PR.

Are you referring to the original proposal, the proposal of the IWG, or both? Reads like the latter.

**Comment by jkowalleck** [comment]
> > the proposal would cause breaking semantic changes. I do not want to bring any breaking change into the spec.
> > Therefore I will drop the aspect 'supplier' entirely from this PR.
> 
> Are you referring to the original proposal, the proposal of the IWG, or both? Reads like the latter.

the latter one.
my [original proposal](https://github.com/CycloneDX/specification/pull/379/commits/4ca69c9cdf81356d7f114ceaa9fca15a7872c97c) would be no breaking in no way.
the idea from the CWG would include breaking changes, literally.

**Review by stevespringett — APPROVED** [review]

**Pull request merged**
