### PR TITLE
[WIP] docs: add testResources JSON `$schema`

### PR DESCRIPTION
**Pull request by jkowalleck**
- add `$schema` to json test resources
- fix strict `$schema` enum

part of #254
blocked by #256
supersedes #138

### CODE REVIEW

**Comment by jkowalleck** [comment]
[failing tests](https://github.com/CycloneDX/specification/actions/runs/5336089618/jobs/9670253638?pr=255) showed the importance to fix the `$schema` enum.
Therefore, I plucked #138.

**Comment by jkowalleck** [comment]
the Java tests still fail.
i assume they do not use the shipped schema files, but the ones found online shomehow.

**Comment by jkowalleck** [comment]
the Java tests still fail.
i assume they do not use the shipped schema files, but the ones found online, or the ones shipped with Java package `org.cyclonedx`.

@stevespringett please help.

**Comment by stevespringett** [comment]
Traditionally, how it's been working is that once changes are made to the schema development branch, those changes are mirrored to the Core Java library and published as a SNAPSHOT release. We keep the snapshots up to date with the latest schemas. It has not been synchronized.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/specification/pull/255#issuecomment-1601845304 
this will not help this very PR or future PRs that change the schema files. Therefore, was created #256 with its acceptance criteria.

**Comment by stevespringett** [comment]
Why are there 144 files changed? We cannot accept this PR.

Also, why would test files be required to have the $schema? That makes absolutely no sense.

For example `$schema": "http://cyclonedx.org/schema/bom-1.2b.schema.json`. If this had been specified for v1.2, we would have had to change all the test files twice (a, and b). We should not have to change existing tests for a bump in schema. That defeats the purpose.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/specification/pull/255#issuecomment-1601939004
> Also, why would test files be required to have the $schema? That makes absolutely no sense.

please read #254 to understand the motivation. then you will see why this makes total sense ;-) 

> If this had been specified for v1.2, we would have had to change all the test files twice (a, and b). We should not have to change existing tests for a bump in schema. That defeats the purpose.

Now you see the hassle everybody goes through who is already referencing the existing schemas files. If we in-place-change the `$id` in the schema without providing the old version still , users might have to adopt and change existing documents.
The (strict)schema pins its own namespace in downstream documents. To fix this, #138 was introduced but never got accepted. 
and now we are where we are.

> Why are there 144 files changed? We cannot accept this PR.

this PR is in the making. no final solution.
current stage showed multiple issues with the current state of the project:
- some tests run against different schema files (snapshots)
- the need to modify `$schema` in a lot of files, because it was modified over the time.
  In contrast, the XSD does not have this behavior -  `1.2 stayed the same, even we are at a 3rd iteration of `1.2`.

**Comment by jkowalleck** [comment]
i might rework the content of this PR, and might come up with a followup.
goal would be, that the test files for CDX1.6+ will have a schema annotated - as of https://github.com/CycloneDX/specification/issues/402

**Comment by jkowalleck** [comment]
Superseded by  #423

**Pull request closed without merging**
