### PR TITLE
Note regarding multiple components in the same BOM

### PR DESCRIPTION
**Pull request by Walter-Haydock**
Per conversation with Paul Horton (https://cyclonedx.slack.com/archives/CVA0G10FN/p1660383842828799), I am adding a note to the JSON schema explaining how to handle multiple instances of the same component (so that it is possible to reflect different analyses for each one).

### CODE REVIEW

**Comment by jkowalleck** [comment]
Hello @Walter-Haydock 

first of all: please also update the description i the other schema definitions, too. XML, protobuf, ...

the current discretion reads:
> An optional identifier which can be used to reference the component elsewhere in the BOM. Every bom-ref MUST be unique within the BOM. 

You suggest to addto the description: 
>  If a component appears multiple times in a BOM, each instance of such component MUST have its own unique bom-ref.

Your addition appears to be already covered by the current description."unique"  means "once in a universe". there is no value in your addition, or is there? Maybe i don't get it. 
On the other hand, your addition is wrong: The `bom-ref` is optional - a "MUST have its own unique bom-ref" is wrong - as the `bom-ref` is still not mandatory.

what do i not see?

**Comment by vuln-exchange** [comment]
Hi @jkowalleck - thanks for the comments. My goal is to answer the same question I had regarding multiple instances of the same component (https://cyclonedx.slack.com/archives/CVA0G10FN/p1660339494343359). The answer wasn't initially obvious to me, so perhaps this is better for an FAQ-type document.

If not, then perhaps the following wording would be more helpful: "If a component appears multiple times in a BOM, each instance of such component with a bom-ref MUST have a separate bom-ref."

I would greatly appreciate your input on this issue, in order to proactively address this type of question in the future.

**Comment by jkowalleck** [comment]
> If a component appears multiple times in a BOM, each instance of such component with a bom-ref MUST have a separate bom-ref.


is this not just another phrasing of 
> Every bom-ref MUST be unique within the BOM.

**Comment by Walter-Haydock** [comment]
Since this misunderstanding might be unique to me, I'll just close out this PR.

**Pull request closed without merging**
