### PR TITLE
Implemented JSF in the core spec

### PR DESCRIPTION
**Pull request by stevespringett**
This implements a prerequisite in #89

### CODE REVIEW

**Review by coderpatros — APPROVED** [review]

**Comment by coderpatros** [comment]
LGTM

I can't remember, but I think you were creating the JSF schema from scratch? I'm wondering if we should [at]cyberphone to see if he could review it too?

**Comment by stevespringett** [comment]
HI @cyberphone. As stated on the prior email thread, we're implementing JSF 0.82 directly into CycloneDX. Would you mind taking a look?

The schema supports the entirety of the JSF spec excluding `extensions`. The way extensions are currently implemented in JSF requires JSON properties to be dynamic and thus the JSON Schema `additionalProperties` value must be set to true, which prohibits the schema from being hardened. So we opted not to support JSF extensions so that our schema could remain hardened. 

Let us know if we captured everything correctly or if there's something we need to change.

Also, do you see any major compatibility issues with excluding extension support?

**Comment by cyberphone** [comment]
I'm impressed!  BTW, I didn't know that JSON schema was that powerful.

If `extensions` is important or not is very application dependent.  Its main purpose is holding additional signatory meta data if there are multiple signers like in https://cyberphone.github.io/doc/security/jsf.html#p256_es256_r2048_rs256_mult-exts-kid.json

I will most certainly reference this work in other contexts.

**Comment by stevespringett** [comment]
@DarthHater can I get approval on this please?

**Pull request merged**
