### PR TITLE
Add `source-distribution` element to `externalReferenceType`

### LINKED ISSUE #98: externalReferences type for "source" packages
Sorry if I overlooked something obvious, but I miss a way to specify a `source` archive url for a component, as logical counterpart to the `distribution` type.

Many ecosystems have the concept of a source and a somehow derived package. In Python's PyPI you have a "wheel" and a "source" package (check https://pypi.org/project/chardet/#files), for Linux packages there are binary and corresponding source packages (check https://packages.debian.org/buster/libgcc1) etc. 

Deriving the correct "source" package for a component isn't always straight-forward, but important for many use-cases (for example for license clearing, for mapping source-level sec advisories to binary components etc.). So it would be very helpful to store them in a CycloneDX BOM in a canonical way. Therefore I suggest to add a `source` type for externalReferences.

Note that this is in most cases not equal to the "vcs" type (which is often some kind of upstream project) because many repositories provide an own `source` archive exactly reflecting what was used when building their "binary" packages. 

Example:

```json
      "name": "chardet",
      "version": "4.0.0",
      "externalReferences": [
        {
          "type": "distribution",
          "url": "https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl",
          "comment": "PyPI wheel file"
        },
        {
          "type": "source",
          "url": "https://files.pythonhosted.org/packages/ee/2d/9cdc2b527e127b4c9db64b86647d567985940ac3698eeabc7ffaccb4ea61/chardet-4.0.0.tar.gz",
          "comment": "PyPI source archive"
        },
        {
          "type": "vcs",
          "url": "https://github.com/chardet/chardet",
          "comment": "upstream repository"
        }
      ]
```

### PR DESCRIPTION
**Pull request by tsjensen**
Resolves #98

After a lot of discussions in #98, I thought it might help to have this PR in order to be as clear as possible about what the proposed change would be that we are discussing.

Please upvote this if you agree! Maybe we are lucky and the thing turns out to be simple. 😄
@stevespringett @jkowalleck Let me know if I missed something, I'll be happy to rework as needed.

Thank you for considering this.

### CODE REVIEW

**Comment by gernot-h** [comment]
Cool, thanks, @tsjensen for taking the initiative here!

**Comment by jkowalleck** [comment]
> Let me know if I missed something, I'll be happy to rework as needed.

protobuff is missing.

**Comment by tsjensen** [comment]
> protobuff is missing.

Dang, right! Fixed now.

**Comment by tsjensen** [comment]
@jkowalleck What do you think now?

**Comment by jkowalleck** [comment]
looks like a promissing draft. 

@stevespringett this looks ready for the IWG

**Review by jkowalleck — APPROVED** [review]

**Comment by tsjensen** [comment]
Glad to hear that! Let me know when the decision for the exact wording is made, and I'll update the PR.

**Comment by jkowalleck** [comment]
@tsjensen please change it to "source-distribution"
and put the enum one over the existing "distribution".

**Comment by tsjensen** [comment]
Working on it!

**Review by stevespringett — APPROVED** [review]

**Comment by jkowalleck** [comment]
@tsjensen @agschrei @gernot-h 

this feature was agreed and accepted in todays meeting. 
CC @stevespringett @coderpatros @DarthHater 

NEXT steps: 
I will rebase/back-merge and fix conflicts SOON :-D 
And then it will be merged to 1.6 dev branch 🚀

**Comment by jkowalleck** [comment]
@tsjensen i just rebased onto latest `1.6-dev` and fixed some conflicts.

ready for merging, @stevespringett

**Comment by jkowalleck** [comment]
ready for merging, @stevespringett

**Comment by jkowalleck** [comment]
@tsjensen i am very sorry, something stupid happened.
after i pushed the rebased and fixed version, github closed this PR and dropped my write-permission to your branhc.
In result, your changes and my fixes were dropped, your branch is just on upstream's HEAD< and this PR was auto-closed by github since there was nothing new. 


I am very sorry for the inconvenience, but ...
could you please redo your changes nd my fixes:
1. add "source-distribution" to the enum
1. add a description to "meta:enum" 
1. push your changes
1. reopen this PR

your previous changes are still there: https://github.com/CycloneDX/specification/commit/037eb89697ba5d400db7641d75554b3e0dc686f2

**Comment by tsjensen** [comment]
Great to hear that it was accepted! No worries about the GitHub mishap, I'll restore stuff tomorrow.

**Comment by tsjensen** [comment]
@jkowalleck I restored the commit on my fork and rebased to the latest 1.6-dev:
<https://github.com/tsjensen/specification/commits/1.6-dev/>

However I seem to lack permissions to reopen the PR. Can *you* try to reopen the PR?  
Then we see if the commit appears back here. If not, then it seems we'll have to do a new PR.

**Comment by jkowalleck** [comment]
thank you for your effort, @tsjensen 

I just reopened this PR, tests are passing.
I am happy to merge your changes.

**Pull request merged**
